services:
    app:
        build:
            context: ./docker
            args:
                USER_ID: "${USER_ID}"
                GROUP_ID: "${GROUP_ID}"
        # restart: always
        user: "${USER_ID}:${GROUP_ID}"
        volumes:
            - ./:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/local-conf.d/:/usr/local/etc/php/local-conf.d/
            - caddy_data:/data
            - caddy_config:/config
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - db
            - node
        tty: true
        ports:
            - "80:80"
            - "443:443"
        command: frankenphp run
        networks:
            - proj-net
    node:
        image: node:lts-alpine
        user: "${USER_ID}:${GROUP_ID}"
        volumes:
            - ./:/app
        environment:
            - NODE_ENV=development
        ports:
            - "3000:3000"
        command: npm run dev
        working_dir: /app
        networks:
            - proj-net
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - ./database/data:/var/lib/postgresql
        ports:
            - "5432:5432"
        networks:
            - proj-net
networks:
    proj-net:
volumes:
    caddy_data:
    caddy_config:
